# FEATURE: move this to the spring cloud config to have one place for all microservices configs management
spring:
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            bootstrap-servers: localhost:9092
            group-id: ${spring.application.name}
            auto-offset-reset: earliest
            enable-auto-commit: false
        producer:
            batch-size: 16384
            buffer-memory: 33554432
            retries: 0
